### ISSUE TITLE
SteamKit fork login issue

### ISSUE THREAD

**Issue by n4bz0r** [aegamesi/SteamTrade#2]
Hello. I'm using your fork of SteamKit-Java, but can't simply log in. I've described my problem here: https://github.com/SteamRE/SteamKit/issues/105. Still can't figure out. I'm simply trying to do smth like this:
```java
steamClient.connect();
```
and after getting connected callback:
```java
steamUser.logOn("login", "passwd");
```
It seems there is problem with proto messages. Maybe you've changed something and did not commit in repository?

**Comment by aegamesi** [comment]
Are you working on Android? 

Please see https://github.com/Top-Cat/ScrapBank.tf/blob/master/src/main/java/uk/co/thomasc/scrapbanktf/Bot.java#L151 for an example of a proper way to log in to the Steam network with SteamKit-Java.

**Comment by n4bz0r** [comment]
Yes on Android. It was typo on first post. I'm doing exactly same this as scrapbank.tf bot using LogOnDetails(). I've tried to do same thing on C# and it works. I think it's something with my steamkit build.

**Comment by aegamesi** [comment]
Have you tried it not on Android?

**Comment by n4bz0r** [comment]
Just made simple console application and tried TopCat's thing. Got same problem.
```java
TcpConnection: Connecting to [208.64.200.201:27017]...
TcpConnection: Connected!
Bot #0: Bot started
CMClient: <- Recv'd EMsg: ChannelEncryptRequest (1303) (Proto: false)
CMClient: Got encryption request. Universe: Public Protocol ver: 1
CMClient: Sent -> EMsg: ChannelEncryptResponse (Proto: false)
CMClient: <- Recv'd EMsg: ChannelEncryptResult (1305) (Proto: false)
CMClient: Encryption result: OK
Bot #0: Connected. Trying to log on
CMClient: Sent -> EMsg: ClientLogon (Proto: true)
java.security.InvalidKeyException: Illegal key size or default parameters
	at javax.crypto.Cipher.checkCryptoPerm(Cipher.java:1011)
	at javax.crypto.Cipher.init(Cipher.java:1209)
	at javax.crypto.Cipher.init(Cipher.java:1153)
	at uk.co.thomasc.steamkit.util.crypto.CryptoHelper.SymmetricEncrypt(CryptoHelper.java:114)
	at uk.co.thomasc.steamkit.networking.steam3.NetFilterEncryption.processOutgoing(NetFilterEncryption.java:20)
	at uk.co.thomasc.steamkit.networking.steam3.TcpConnection.send(TcpConnection.java:112)
	at uk.co.thomasc.steamkit.steam3.CMClient.send(CMClient.java:263)
	at uk.co.thomasc.steamkit.steam3.handlers.steamuser.SteamUser.logOn(SteamUser.java:106)
	at com.n4bz0r.steambotconsole.Bot$1.call(Bot.java:68)
	at com.n4bz0r.steambotconsole.Bot$1.call(Bot.java:62)
	at uk.co.thomasc.steamkit.steam3.steamclient.callbackmgr.CallbackMsg.handle(CallbackMsg.java:40)
	at com.n4bz0r.steambotconsole.Bot.handleSteamMessage(Bot.java:62)
	at com.n4bz0r.steambotconsole.Bot.update(Bot.java:51)
	at com.n4bz0r.steambotconsole.Main$BotThread.run(Main.java:42)
	at java.lang.Thread.run(Thread.java:744)
```

**Comment by aegamesi** [comment]
That error means you don't have your cryptography library properly set up.
Due to US export laws, you have to separately download the Java
Cryptography Extension (JCE).

**Comment by n4bz0r** [comment]
It works as console app but there is same error as before on android.

**Comment by aegamesi** [comment]
You need to make sure bouncy/spongycastle and JCE are properly configured.

**Comment by n4bz0r** [comment]
I can install this policies on local machine but how do I configure android the same way?
Found this: http://stackoverflow.com/questions/7258016/unlimited-strength-jce-and-android but doesn't really help

**Comment by n4bz0r** [comment]
I'm getting this output after building the project: 
```java
-------------------------------------------------------------------------------
Test set: org.spout.steamkit.util.crypto.CryptoHelperTest
-------------------------------------------------------------------------------
Tests run: 4, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.219 sec <<< FAILURE!
testSymetric(org.spout.steamkit.util.crypto.CryptoHelperTest)  Time elapsed: 0.216 sec  <<< ERROR!
java.lang.SecurityException: JCE cannot authenticate the provider SC
	at javax.crypto.Cipher.getInstance(Cipher.java:642)
	at javax.crypto.Cipher.getInstance(Cipher.java:580)
	at uk.co.thomasc.steamkit.util.crypto.CryptoHelper.SymmetricDecrypt(CryptoHelper.java:160)
	at org.spout.steamkit.util.crypto.CryptoHelperTest.testSymetric(CryptoHelperTest.java:49)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        <...>
Caused by: java.util.jar.JarException: file:/C:/Users/newbie/.m2/repository/com/madgag/scprov-jdk15on/1.47.0.2/scprov-jdk15on-1.47.0.2.jar has unsigned entries - org/spongycastle/i18n/LocalizedMessage$FilteredArguments.class
	at javax.crypto.JarVerifier.verifySingleJar(JarVerifier.java:462)
	at javax.crypto.JarVerifier.verifyJars(JarVerifier.java:322)
	at javax.crypto.JarVerifier.verify(JarVerifier.java:250)
	at javax.crypto.JceSecurity.verifyProviderJar(JceSecurity.java:161)
	at javax.crypto.JceSecurity.getVerificationResult(JceSecurity.java:187)
	at javax.crypto.Cipher.getInstance(Cipher.java:638)
	... 32 more
```

**Comment by aegamesi** [comment]
There is something wrong with your spongycastle jar. I don't know what
exactly... Make sure you're downloading the correct jar.

**Comment by n4bz0r** [comment]
I'm using one you've specified in pom.xml
```xml
<dependency>
	<groupId>com.madgag</groupId>
	<artifactId>scpg-jdk15on</artifactId>
	<version>1.47.0.2</version>
</dependency>
```
I've tried different versions from repo you've specified, different versions from here https://rtyley.github.io/spongycastle/. Can you just upload somewhere your spongycastle jars to make sure?

**Comment by FabianTerhorst** [comment]
write this in your gradle file:

    compile 'com.madgag.spongycastle:core:1.51.0.0'
    compile 'com.madgag.spongycastle:prov:1.51.0.0'
